routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Route::get('/', 'PagesController@home');

Route::get('email', function(){
     return new App\Mail\LoginCredencials( App\User::first(), '123434');
});

Route::get('email2', function(){
     return new App\Mail\ActivationCapturist( App\User::first(), date('Y-m-d H:i:s'));
});

Route::group([
     'prefix' => 'admin',
     'namespace' => 'Admin',
     'middleware' => 'auth'],
function(){
     Route::get('/', 'AdminController@index')->name('dashboard');
     Route::resource('user', 'UserController', ['as' => 'admin']);
     Route::resource('leader', 'LeaderController', ['as' => 'admin']);
     Route::resource('capturist', 'CapturistController', ['as' => 'admin']);
     Route::resource('candidate', 'CandidateController', ['as' => 'admin']);
     Route::resource('search', 'SearchController', ['as' => 'admin']);
     Route::resource('company', 'CompanyController', ['as' => 'admin']);
     Route::resource('study', 'StudyController', ['as' => 'admin']);
     Route::resource('category', 'CategoryController', ['as' => 'admin']);
     Route::resource('survey', 'SurveyController', ['as' => 'admin']);

     Route::group(['prefix' => '{category_id}'], function($category_id){
           Route::resource('category', 'CategoryController');
      });

      Route::group(['prefix' => '{user_id}'], function($user_id){
           Route::resource('answer', 'AnswerController');
      });

      Route::get('answer/create/{user_id}/{survey_id}', 'AnswerController@create')->name('answer.create');
      Route::get('answer/edit/{user_id}/{survey_id}', 'AnswerController@edit')->name('answer.edit');

      Route::group(['prefix' => '{category_id}'], function($category_id){
           Route::resource('brand', 'BrandController');
      });

      // Pagina de expotar survey
     Route::get('export_survey/{survey}', 'SurveyController@export_survey')->name('admin.export_survey');

     // Actualizar permisos de usuarios
     Route::put('leader/{user}/permissions', 'UserPermissionsController@update')->name('admin.leader.permissions.update');

     // Activar capturistas
     Route::post('capturista/activar_capturistas', 'CapturistController@activar_capturistas')->name('admin.capturista.activar_capturistas');

     // Pagina de buscador
     Route::get('buscador', 'CandidateController@buscador')->name('admin.buscador');

     // Pagina de buscador
     Route::get('export_search/{search_id}', 'CandidateController@export_search')->name('admin.export_search');

     // Obtener municipios
     Route::get('municipios', 'DireccionesController@municipios')->name('admin.municipios');

     // Obtener localidades
     Route::get('localidades', 'DireccionesController@localidades')->name('admin.localidades');

     // Obtener nuevos candidatos
     Route::get('new_candidate', 'CandidateController@new_candidate')->name('admin.new_candidate');

     // Obtener informar a capturistas
     Route::post('send_comment', 'CandidateController@send_comment')->name('admin.send_comment');

     // Obtener participantes buscador
     Route::get('filter_participants', 'CandidateController@filter_participants')->name('admin.filter_participants');

     // Perfil
     Route::get('perfil', 'CandidateController@perfil')->name('admin.perfil');
     Route::put('edit_perfil', 'CandidateController@edit_perfil')->name('admin.edit_perfil');


     Route::post('assigned_study', 'CandidateController@assigned_study')->name('admin.assigned_study');
     Route::get('assigned_study_id/{id}', 'CandidateController@assigned_study_id')->name('admin.assigned_study_id');
     Route::delete('destroy_assigned_study/{id}', 'CandidateController@destroy_assigned_study')->name('admin.destroy_assigned_study');
});

// Obtener municipios
Route::get('municipios', 'Admin\DireccionesController@municipios')->name('municipios');

// Obtener localidades
Route::get('localidades', 'Admin\DireccionesController@localidades')->name('localidades');

// Desactivar capturistas con cron
Route::get('capturista/desactivar_capturistas', 'PagesController@deactivate_user')->name('capturista.desactivar_capturistas');

// Authentication Routes...
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::get('logout', 'Auth\LoginController@logout')->name('logout');

// Registration Routes...
Route::get('register', 'Admin\CandidateController@showRegistrationForm')->name('register');
Route::put('registro', 'Admin\CandidateController@registro')->name('registro');

// Password Reset Routes...
Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('password/reset', 'Auth\ResetPasswordController@reset');

app/Study.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Study extends Model
{
     public $timestamps = true;

     protected $fillable = [
          'name', 'company_id', 'study_date', 'removed', 'number_participants'
     ];

     public function company()
     {
          return $this->belongsTo( Company::class );
     }
}

app/Http/Controllers/Admin/StudyController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Study;
use App\Company;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class StudyController extends Controller
{
     /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
     public function index()
     {
          $studys = Study::where('removed', 0)->get();
          return view('admin.study.index', compact('studys'));

     }

     /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
     public function create()
     {
          $study = new Study;
          $companys = Company::where('removed', 0)->get();
          return view('admin.study.create', compact('study','companys'));
     }

     /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
     public function store(Request $request)
     {
          $data = $request->validate([
               'name' => 'required|string|max:255'
          ]);

          $data['name'] = request('name');
          $data['company_id'] = request('company_id');
          $data['study_date'] = request('study_date');
          $data['number_participants'] = request('number_participants');

          $study = Study::create($data);

          return redirect()->route('admin.study.index')->with('success', 'Estudio registrado');

     }

     /**
     * Display the specified resource.
     *
     * @param  \App\Study  $study
     * @return \Illuminate\Http\Response
     */
     public function show(Study $study)
     {

     }

     /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Study  $study
     * @return \Illuminate\Http\Response
     */
     public function edit(Study $study)
     {
          $companys = Company::where('removed', 0)->get();
          return view('admin.study.edit', compact('study', 'companys'));

     }

     /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Study  $study
     * @return \Illuminate\Http\Response
     */
     public function update(Request $request, Study $study)
     {
          $data = $request->validate([
               'name' => 'required|string|max:255'
          ]);

          $data['name'] = request('name');
          $data['company_id'] = request('company_id');
          $data['study_date'] = request('study_date');
          $data['number_participants'] = request('number_participants');

          $study->update( $data );

          return redirect()->route('admin.study.index')->with('success', 'Estudio editado');
     }

     /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Study  $study
     * @return \Illuminate\Http\Response
     */
     public function destroy(Study $study)
     {
          $data['removed'] = 1;
          $study->update( $data );
          return back()->with('success', 'Estudio eliminado');
     }
}

resources/views/admin/study/create.blade.php
@extends('admin.layout')

@section('content')
@if(auth()->user()->can('Editar roles'))
<div class="col-md-12">
@else
<div class="col-md-12 ml-auto mr-auto">
@endif
     <form class="form" method="post" action="{{ route('admin.study.store') }}">
          {{ csrf_field() }}

          <div class="card">
               <div class="card-header ">
                    <div class="card-header">
                         <h4 class="card-title">Datos del estudio</h4>
                    </div>
               </div>
               <div class="card-body ">
                    <div class="row">
                         <div class="col-md-12">
                              @if($errors->any())
                                   <ul class="list-group">
                                        @foreach($errors->all() as $key => $error)
                                             <li class="list-group-item list-group-item-danger"> {{ $error }}</li>
                                        @endforeach
                                   </ul>
                              @endif
                         </div>
                         <div class="col-md-12">
                              <div class="row">
                                   <div class="col-md-8">
                                        <div class="form-group">
                                             <label for="name">Nombre</label>
                                             <input type="text" name="name" class="form-control" value="{{ old('name') }}" placeholder="Nombre">
                                        </div>
                                   </div>
                                   <div class="col-md-4">
                                        <div class="form-group">
                                             <label for="email">Fecha estudio</label>
                                             <input type="text" name="study_date" autocomplete="off" class="form-control datetimepicker" value="{{ old('study_date') }}" placeholder="Fecha estudio">
                                        </div>
                                   </div>

                              </div>
                              <div class="row">
                                   <div class="col-md-8">
                                        <div class="form-group">
                                             <label for="email">Cliente / Empresa</label>
                                             <select class="form-control" name="company_id"  >
                                                  <option value="" hidden> -- Seleccione una opción</option>
                                                  @foreach ($companys as $key => $company)
                                                       <option value="{{ $company->id }}">{{ $company->name }}</option>
                                                  @endforeach
                                             </select>
                                        </div>
                                   </div>
                              </div>
                              <div class="row">
                                   <div class="col-md-8">
                                        <h5>Requerimientos del cliente</h5>
                                   </div>
                              </div>
                              <div class="row">
                                   <div class="col-md-6">
                                        <div class="form-group">
                                             <label for="email">Número de participantes</label>
                                             <input type="number" name="number_participants" class="form-control" value="{{ old('name') }}" placeholder="Número de participantes">
                                        </div>
                                   </div>
                              </div>
                         </div>
                    </div>

                    <button type="submit" class="btn btn-info btn-fill pull-right">Crear estudio</button>
                    <a href="{{ route('admin.study.index') }}" class="btn btn-default btn-fill pull-left">Cancelar</a>
                    <div class="clearfix"></div>
               </div>
          </div>

     </form>
</div>
@stop

@push('style')
<link href="https://cdnjs.cloudflare.com/ajax/libs/multi-select/0.9.12/css/multi-select.min.css" rel="stylesheet" type="text/css" />
<link href="https://unpkg.com/gijgo@1.9.13/css/gijgo.min.css" rel="stylesheet" type="text/css" />
<link href="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.css" rel="stylesheet" type="text/css" />
<style media="screen">
input.form-control.datetimepicker.gj-textbox-md{
     border: 1px solid #e3e3e3;
     padding-left: 10px;
}
input.form-control.datetimepicker2.gj-textbox-md{
     border: 1px solid #e3e3e3;
     padding-left: 10px;
}
i.gj-icon{
     margin-top: 8px;
     margin-right: 5px;
}
div#ms-optgroup{
     width: 100%;
}
</style>
@endpush

@push('scripts')
<script src="https://unpkg.com/gijgo@1.9.13/js/gijgo.min.js" type="text/javascript"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/multi-select/0.9.12/js/jquery.multi-select.min.js" type="text/javascript"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.js" type="text/javascript"></script>

<script>
$( document ).ready(function() {

     $('.datetimepicker').datepicker({
          format: 'yyyy-mm-dd'
     });

});
</script>
@endpush

resources/views/admin/study/edit.blade.php
@extends('admin.layout')

@section('content')
@if(auth()->user()->can('Editar roles'))
<div class="col-md-12">
@else
<div class="col-md-12 ml-auto mr-auto">
@endif
     <form class="form" method="post" action="{{ route('admin.study.update', $study) }}">
          {{ csrf_field() }} {{ method_field('PUT') }}

          <div class="card">
               <div class="card-header ">
                    <div class="card-header">
                         <h4 class="card-title">Datos del estudio</h4>
                    </div>
               </div>
               <div class="card-body ">
                    <div class="row">
                         <div class="col-md-12">
                              @if($errors->any())
                                   <ul class="list-group">
                                        @foreach($errors->all() as $key => $error)
                                             <li class="list-group-item list-group-item-danger"> {{ $error }}</li>
                                        @endforeach
                                   </ul>
                              @endif
                         </div>
                         <div class="col-md-12">
                              <div class="row">
                                   <div class="col-md-8">
                                        <div class="form-group">
                                             <label for="name">Nombre</label>
                                             <input type="text" name="name" class="form-control" value="{{ $study->name }}" placeholder="Nombre">
                                        </div>
                                   </div>
                                   <div class="col-md-4">
                                        <div class="form-group">
                                             <label for="email">Fecha estudio</label>
                                             <input type="text" name="study_date" autocomplete="off" class="form-control datetimepicker" value="{{ $study->study_date }}" placeholder="Fecha estudio">
                                        </div>
                                   </div>

                              </div>
                              <div class="row">
                                   <div class="col-md-8">
                                        <div class="form-group">
                                             <label for="email">Cliente / Empresa</label>
                                             <select class="form-control" name="company_id"  >
                                                  <option value="" hidden> -- Seleccione una opción</option>
                                                  @foreach ($companys as $key => $company)
                                                       <option
                                                            value="{{ $company->id }}"
                                                            @if($study->company_id == $company->id) selected @endif
                                                            >{{ $company->name }}</option>
                                                  @endforeach
                                             </select>
                                        </div>
                                   </div>
                              </div>
                              <div class="row">
                                   <div class="col-md-8">
                                        <h5>Requerimientos del cliente</h5>
                                   </div>
                              </div>
                              <div class="row">
                                   <div class="col-md-6">
                                        <div class="form-group">
                                             <label for="email">Número de participantes</label>
                                             <input type="number" name="number_participants" class="form-control" value="{{ $study->number_participants }}" placeholder="Número de participantes">
                                        </div>
                                   </div>
                              </div>
                         </div>
                    </div>

                    <button type="submit" class="btn btn-info btn-fill pull-right">Editar estudio</button>
                    <a href="{{ route('admin.study.index') }}" class="btn btn-default btn-fill pull-left">Cancelar</a>
                    <div class="clearfix"></div>
               </div>
          </div>

     </form>
</div>
@stop

@push('style')
<link href="https://cdnjs.cloudflare.com/ajax/libs/multi-select/0.9.12/css/multi-select.min.css" rel="stylesheet" type="text/css" />
<link href="https://unpkg.com/gijgo@1.9.13/css/gijgo.min.css" rel="stylesheet" type="text/css" />
<link href="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.css" rel="stylesheet" type="text/css" />
<style media="screen">
input.form-control.datetimepicker.gj-textbox-md{
     border: 1px solid #e3e3e3;
     padding-left: 10px;
}
input.form-control.datetimepicker2.gj-textbox-md{
     border: 1px solid #e3e3e3;
     padding-left: 10px;
}
i.gj-icon{
     margin-top: 8px;
     margin-right: 5px;
}
div#ms-optgroup{
     width: 100%;
}
</style>
@endpush

@push('scripts')
<script src="https://unpkg.com/gijgo@1.9.13/js/gijgo.min.js" type="text/javascript"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/multi-select/0.9.12/js/jquery.multi-select.min.js" type="text/javascript"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.js" type="text/javascript"></script>

<script>
$( document ).ready(function() {

     $('.datetimepicker').datepicker({
          format: 'yyyy-mm-dd'
     });

});
</script>
@endpush

resources/views/admin/study/index.blade.php
@extends('admin.layout')

@section('content')
<div class="col-md-12">
     <div class="card strpied-tabled-with-hover">
          <div class="card-header ">
               <h4 class="card-title">Estudios</h4>
               <p class="card-category">Lista de cliente</p>
               <a href="{{ route('admin.study.create') }}" class="btn btn-success btn-wd" style="float: right; margin-top: -50px;">
                    <i class="fa fa-plus"></i> Nuevo
               </a>
          </div>
          <div class="card-body table-responsive">
               <table class="table table-hover table-striped table_js">
                    <thead>
                         <tr>
                              <th>ID</th>
                              <th>Nombre</th>
                              <th>Cliente</th>
                              <th class="text-center">Número de participantes</th>
                              <th class="text-center">Fecha estudio</th>
                              <th class="text-center"><i class="nc-icon nc-preferences-circle-rotate"></i></th>
                         </tr>
                    </thead>

                    <tbody>
                         @foreach ($studys as $studys)
                         <tr>
                              <td>{{ $studys->id }}</td>
                              <td>{{ $studys->name }}</td>
                              <td>{{ $studys->company->name }}</td>
                              <td class="text-center">{{ $studys->number_participants }}</td>
                              @if($studys->study_date)
                              <td class="text-center">{{ \Carbon\Carbon::parse($studys->study_date)->format('d/m/Y')}}</td>
                              @else
                              <td class="text-center">S / F</td>
                              @endif
                              <td class="text-center">

                                   @can('Editar Capturista')
                                   <a href="{{ route('admin.study.edit', $studys) }}"
                                   class="btn btn-sm btn-info btn-outline"
                                   > <i class="fa fa-pencil"></i> </a>
                                   @endcan
                                   @can('Eliminar Capturista')
                                   <form method="POST"
                                   action="{{ route('admin.study.destroy', $studys) }}"
                                   style="display:inline">
                                   {{ csrf_field() }} {{ method_field('DELETE') }}
                                   <button class="btn btn-sm btn-danger btn-outline"
                                   onclick="return confirm('¿ Estás seguro de querer eliminar este estudio ?')"
                                   >
                                   <i class="fa fa-trash"></i>
                              </button>
                         </form>
                         @endcan

                    </td>
               </tr>
               @endforeach
          </tbody>
          <tfoot>
               <tr>
                    <td colspan="6">
                         <button style="display:none; float:right;" id="btn_activar"  type="button" data-toggle="modal" data-target="#activar_capturistas" class="btn btn-success pull-left">Activar usuarios</button>
                    </td>
               </tr>
          </tfoot>
     </table>
</div>
</div>
</div>



<div class="modal fade modal-mini modal-primary " id="activar_capturistas" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
     <form method="POST" action="{{ route('admin.capturista.activar_capturistas') }}">
          {{ csrf_field() }}
          <div class="modal-dialog">
               <div class="modal-content">
                    <div class="modal-header justify-content-center">
                         <div class="modal-profile">
                              <i class="nc-icon nc-time-alarm"></i>
                         </div>
                    </div>
                    <div class="modal-body text-center">
                         <p> Tiempo actividad : </p>
                         <input type="text" style="text-align:center;" name="tiempo" required class="form-contorl clockpicker" value="">
                         <input type="hidden" name="ip" id="ip" value="">
                         <div id="list_user_active">
                         </div>
                    </div>
                    <div class="modal-footer">
                         <div class="col-md-12">
                              <button type="button" class="btn btn-default btn-simple" data-dismiss="modal">Cancelar</button>
                              <button type="submit" class="btn btn-primary">Activar</button>
                         </div>
                    </div>
               </div>
          </div>
     </form>
</div>

@stop
<!-- Estilos pasarlos al layout -->
@push('style')
<style media="screen">
.popover.clockpicker-popover.bottom.clockpicker-align-left{
    z-index: 9999;
}
</style>

@endpush
<!-- Escripts pasarlos al layout -->
@push('scripts')
<script>
$( document ).ready(function() {

     $.getJSON('https://api.ipify.org?format=json', function(data){
          $('#ip').val(data.ip);
     });

     $('.l_capturista').change(function() {
          var ver_boton = false;
          $('#btn_activar').hide();
          $('#list_user_active').html('');
          $('.l_capturista').each(function () {
               if (this.checked) {
                    $('#btn_activar').show();
                    $('#list_user_active').append('<input type="hidden" name="user[]" value="'+this.value+'" />');
               }
          });

     });

});
</script>
@endpush

resources/views/admin/study/show.blade.php
@extends('admin.layout')

@section('content')
<div class="col-md-6">
     <div class="card card-user">
          <div class="card-header no-padding">
               <div class="card-image">
                    <img src="/img/background-perfil.jpg" alt="...">
               </div>
          </div>
          <div class="card-body ">
               <div class="author">
                    <a href="#">
                         <img class="avatar border-gray" src="https://us.123rf.com/450wm/tuktukdesign/tuktukdesign1608/tuktukdesign160800042/61010829-icono-de-usuario-hombre-perfil-hombre-de-negocios-avatar-ilustraci%C3%B3n-vectorial-persona-glifo.jpg?ver=6" alt="...">
                    </a>
                    <p class="card-description">
                         <h6 class="card-title">Número identificador</h6>
                         {{ $capturist->id }}
                         <hr>
                         <h6 class="card-title">Nombre completo</h6>
                         {{ $capturist->name }}
                         <hr>
                         <h6 class="card-title">Correo</h6>
                         {{ $capturist->email }}
                         <hr>

                         <h6 class="card-title">Estatus</h6>
                         @if($capturist->status == 1)
                              <h6><span class="badge badge-success">Activo</span></h6>
                         @else
                              <h6><span class="badge badge-danger">Inactivo</span></h6>
                         @endif

                         <hr>

                         <h6 class="card-title">Fecha registro</h6>
                         {{ $capturist->created_at }}
                    </p>
               </div>
          </div>

     </div>
</div>
<div class="col-md-6">
     <div class="card card-user">
          <div class="card-header">
               <h4 class="card-title">Permiso adicionales</h4>
               <p class="card-category">permisos extras asignados </p>
          </div>
          <div class="card-body ">
                    <p class="card-description">
                         @forelse ($capturist->permissions as $permission)
                              <h6 class="card-title">{{ $permission->name }}</h6>
                              @unless($loop>last)
                                   <hr>
                              @endunless
                         @empty
                              <h6 class="card-title">No tiene permisos adicionales</h6>
                         @endforelse
                    </p>
          </div>

     </div>
</div>
@stop