routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Route::get('/', 'PagesController@home');

Route::get('email', function(){
     return new App\Mail\LoginCredencials( App\User::first(), '123434');
});

Route::get('email2', function(){
     return new App\Mail\ActivationCapturist( App\User::first(), date('Y-m-d H:i:s'));
});

Route::group([
     'prefix' => 'admin',
     'namespace' => 'Admin',
     'middleware' => 'auth'],
function(){
     Route::get('/', 'AdminController@index')->name('dashboard');
     Route::resource('user', 'UserController', ['as' => 'admin']);
     Route::resource('leader', 'LeaderController', ['as' => 'admin']);
     Route::resource('capturist', 'CapturistController', ['as' => 'admin']);
     Route::resource('candidate', 'CandidateController', ['as' => 'admin']);
     Route::resource('search', 'SearchController', ['as' => 'admin']);
     Route::resource('company', 'CompanyController', ['as' => 'admin']);
     Route::resource('study', 'StudyController', ['as' => 'admin']);
     Route::resource('category', 'CategoryController', ['as' => 'admin']);
     Route::resource('survey', 'SurveyController', ['as' => 'admin']);

     Route::group(['prefix' => '{category_id}'], function($category_id){
           Route::resource('category', 'CategoryController');
      });

      Route::group(['prefix' => '{user_id}'], function($user_id){
           Route::resource('answer', 'AnswerController');
      });

      Route::get('answer/create/{user_id}/{survey_id}', 'AnswerController@create')->name('answer.create');
      Route::get('answer/edit/{user_id}/{survey_id}', 'AnswerController@edit')->name('answer.edit');

      Route::group(['prefix' => '{category_id}'], function($category_id){
           Route::resource('brand', 'BrandController');
      });

      // Pagina de expotar survey
     Route::get('export_survey/{survey}', 'SurveyController@export_survey')->name('admin.export_survey');

     // Actualizar permisos de usuarios
     Route::put('leader/{user}/permissions', 'UserPermissionsController@update')->name('admin.leader.permissions.update');

     // Activar capturistas
     Route::post('capturista/activar_capturistas', 'CapturistController@activar_capturistas')->name('admin.capturista.activar_capturistas');

     // Pagina de buscador
     Route::get('buscador', 'CandidateController@buscador')->name('admin.buscador');

     // Pagina de buscador
     Route::get('export_search/{search_id}', 'CandidateController@export_search')->name('admin.export_search');

     // Obtener municipios
     Route::get('municipios', 'DireccionesController@municipios')->name('admin.municipios');

     // Obtener localidades
     Route::get('localidades', 'DireccionesController@localidades')->name('admin.localidades');

     // Obtener nuevos candidatos
     Route::get('new_candidate', 'CandidateController@new_candidate')->name('admin.new_candidate');

     // Obtener informar a capturistas
     Route::post('send_comment', 'CandidateController@send_comment')->name('admin.send_comment');

     // Obtener participantes buscador
     Route::get('filter_participants', 'CandidateController@filter_participants')->name('admin.filter_participants');

     // Perfil
     Route::get('perfil', 'CandidateController@perfil')->name('admin.perfil');
     Route::put('edit_perfil', 'CandidateController@edit_perfil')->name('admin.edit_perfil');


     Route::post('assigned_study', 'CandidateController@assigned_study')->name('admin.assigned_study');
     Route::get('assigned_study_id/{id}', 'CandidateController@assigned_study_id')->name('admin.assigned_study_id');
     Route::delete('destroy_assigned_study/{id}', 'CandidateController@destroy_assigned_study')->name('admin.destroy_assigned_study');
});

// Obtener municipios
Route::get('municipios', 'Admin\DireccionesController@municipios')->name('municipios');

// Obtener localidades
Route::get('localidades', 'Admin\DireccionesController@localidades')->name('localidades');

// Desactivar capturistas con cron
Route::get('capturista/desactivar_capturistas', 'PagesController@deactivate_user')->name('capturista.desactivar_capturistas');

// Authentication Routes...
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::get('logout', 'Auth\LoginController@logout')->name('logout');

// Registration Routes...
Route::get('register', 'Admin\CandidateController@showRegistrationForm')->name('register');
Route::put('registro', 'Admin\CandidateController@registro')->name('registro');

// Password Reset Routes...
Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('password/reset', 'Auth\ResetPasswordController@reset');

app/Http/Controllers/Admin/CapturistController.php
<?php

namespace App\Http\Controllers\Admin;

use App\User;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Http\Requests\UpdateUserRequest;
use Spatie\Permission\Models\Permission;
use Spatie\Permission\Models\Roles;
use App\Events\UserWasCreated;
use App\Events\UserWasActivated;

class CapturistController extends Controller
{
     /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
     public function index()
     {
          $users = User::role('Capturista')->get();
           return view('admin.capturist.index', compact('users'));
     }

     /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
     public function create()
     {
         $permissions = Permission::pluck('name', 'id');
         $leader = new User;
         return view('admin.capturist.create', compact('leader', 'permissions'));
     }

     /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
     public function store(Request $request)
     {
          $data = $request->validate([
             'name' => 'required|string|max:255',
            'email' => 'required|string|email|max:255|unique:users'
        ]);

        $data['password'] = str_random(8);
        $data['status'] = request('status') == 1 ? 1 : 0 ;

        $user = User::create($data);

        $user->assignRole('Capturista');

        if ($request->filled('permissions')) {
             $user->givePermissionTo($request->permissions);
        }

        UserWasCreated::dispatch($user, $data['password']);

        return redirect()->route('admin.capturist.index')->with('success', 'Capturista registrado');

     }

     /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
     public function show(User $capturist)
     {
         return view('admin.capturist.show', compact('capturist'));
     }

     /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
     public function edit(User $capturist)
     {
          $permissions = Permission::pluck('name', 'id');
          return view('admin.capturist.edit', compact('capturist', 'permissions'));
     }

     /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
     public function update(Request $request, User $capturist)
     {
         $data = $request->validate([
              'name' => 'required|string|max:255',
            'email' => 'required|string|email|max:255|unique:users,email,'.$capturist->id,
         ]);

         if($request->filled('password')) {
            $data =  $request->validate([
                   'password' => 'confirmed', 'min:7',
              ]);
         }

         $data['status'] = request('status') == 1 ? 1 : 0 ;


         $capturist->update( $data );

         return redirect()->route('admin.capturist.index')->with('success', 'Capturista actualizado');
     }

     /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
     public function destroy(User $capturist)
     {
          $capturist->delete();
          return back()->with('success', 'Capturist@ eliminado');
     }

     // public function activar_capturistas(Request $request)
     public function activar_capturistas(Request $request)
     {
          $tiempo  = request('tiempo');
          $ip  = request('ip');
          foreach ( request('user') as  $usr) {
               $user = User::where('id', $usr)->first();
               $user->status = 1;
               $user->ip = request('ip');
               $user->time_active = request('tiempo');
               $user->activation_date = date("Y-m-d H:i:s");
               $user->save();

     
               UserWasActivated::dispatch($user, $this->calcular_fecha(date("Y-m-d H:i:s"), request('tiempo').':00' ));

          }
          return back()->with('success', 'Capturist@s activado(s) correctamente');

     }

     public function calcular_fecha($fecha_activacion, $tiempo)
     {
          $timpo_array = explode(":", $tiempo);
          $str = '+'.$timpo_array[0].' hour +'.$timpo_array[1].' minutes +'.$timpo_array[2].' seconds';
          return $cenvertedTime = date('Y-m-d H:i:s', strtotime($str, strtotime($fecha_activacion)) );
     }
}

resources/views/admin/capturist/create.blade.php
@extends('admin.layout')

@section('content')
@if(auth()->user()->can('Editar roles'))
<div class="col-md-12">
@else
<div class="col-md-6 ml-auto mr-auto">
@endif
     <form class="form" method="post" action="{{ route('admin.capturist.store') }}">
          {{ csrf_field() }}

          <div class="card">
               <div class="card-header ">
                    <div class="card-header">
                         <h4 class="card-title">Datos personales</h4>
                    </div>
               </div>
               <div class="card-body ">
                    <div class="row">
                         <div class="col-md-12">
                              @if($errors->any())
                                   <ul class="list-group">
                                        @foreach($errors->all() as $key => $error)
                                             <li class="list-group-item list-group-item-danger"> {{ $error }}</li>
                                        @endforeach
                                   </ul>
                              @endif
                         </div>
                         @if(auth()->user()->can('Editar roles'))
                         <div class="col-md-6">
                         @else
                         <div class="col-md-12">
                         @endif
                              <div class="row">
                                   <div class="col-md-12">
                                        <div class="form-group">
                                             <label for="name">Nombre</label>
                                             <input type="text" name="name" class="form-control" value="{{ old('name') }}" placeholder="Nombre">
                                        </div>
                                   </div>

                              </div>
                              <div class="row">
                                   <div class="col-md-12">
                                        <div class="form-group">
                                             <label for="email">Correo</label>
                                             <input type="email" name="email" class="form-control" value="{{ old('email') }}" placeholder="Correo">
                                        </div>
                                   </div>
                              </div>
                              <div class="row">
                                   <div class="col-md-12">
                                        <div class="form-group">
                                             <label for="status">Estatus</label><br>
                                             <div class="onoffswitch">
                                                 <input type="checkbox" name="status" value="1"  @if( old('status') == 1 ) checked @endif class="onoffswitch-checkbox" id="myonoffswitch">
                                                 <label class="onoffswitch-label" for="myonoffswitch">
                                                     <span class="onoffswitch-inner"></span>
                                                     <span class="onoffswitch-switch"></span>
                                                 </label>
                                             </div>
                                        </div>
                                   </div>
                              </div>
                         </div>
                         @can('Editar roles')
                         <div class="col-md-6">
                              @include('admin.permissions-checkboxes')
                         </div>
                         @endcan
                         <div class="col-md-12">
                              <hr>
                         </div>
                         <div class="col-md-12">
                              <span class="help-block"> La contraseña será generada y enviada al nuevo usuario vía correo.</span>
                         </div>
                         <div class="col-md-12">
                              <hr>
                         </div>
                    </div>

                    <button type="submit" class="btn btn-info btn-fill pull-right">Crear usuario</button>
                    <a href="{{ route('admin.leader.index') }}" class="btn btn-default btn-fill pull-left">Cancelar</a>
                    <div class="clearfix"></div>
               </div>
          </div>

     </form>
</div>
@stop

resources/views/admin/capturist/edit.blade.php
@extends('admin.layout')

@section('content')
@if(auth()->user()->can('Editar roles'))
<div class="col-md-6">
@else
<div class="col-md-6 ml-auto mr-auto">
@endif
     <form class="form" method="post" action="{{ route('admin.capturist.update', $capturist) }}">
          <div class="card ">
               <div class="card-header ">
                    <div class="card-header">
                         <h4 class="card-title">Datos personales</h4>
                    </div>
               </div>
               <div class="card-body ">
                    <div class="row">
                         <div class="col-md-12">
                              @if($errors->any())
                                   <ul class="list-group">
                                        @foreach($errors->all() as $key => $error)
                                             <li class="list-group-item list-group-item-danger"> {{ $error }}</li>
                                        @endforeach
                                   </ul>
                              @endif
                         </div>
                    </div>
                    <div class="row">
                         {{ csrf_field() }} {{ method_field('PUT') }}
                         <div class="col-md-12">
                              <div class="form-group">
                                   <label for="name">Nombre</label>
                                   <input type="text" name="name" class="form-control" value="{{ old('name', $capturist->name) }}" placeholder="Nombre">
                              </div>
                         </div>
                    </div>
                    <div class="row">
                         <div class="col-md-12">
                              <div class="form-group">
                                   <label for="email">Correo</label>
                                   <input type="email" name="email" class="form-control" value="{{ old('email', $capturist->email) }}" placeholder="Correo">
                              </div>
                         </div>
                    </div>
                    <div class="row">
                         <div class="col-md-12">
                              <div class="form-group">
                                   <label for="status">Estatus</label><br>
                                   <div class="onoffswitch">
                                       <input type="checkbox"
                                        name="status"
                                        value="1"
                                        @if( old('status', $capturist->status) == 1 ) checked @endif
                                        class="onoffswitch-checkbox"
                                        id="myonoffswitch" >
                                       <label class="onoffswitch-label" for="myonoffswitch">
                                           <span class="onoffswitch-inner"></span>
                                           <span class="onoffswitch-switch"></span>
                                       </label>
                                   </div>
                              </div>
                         </div>
                    </div>
                    <div class="row">
                         <div class="col-md-12">
                              <div class="form-group">
                                   <label for="password">Contraseña</label>
                                   <input type="password" name="password" class="form-control"  placeholder="Contraseña">
                                   <span class="help-block">Dejar en blanco para no cambiar la contraseña</span>
                              </div>
                         </div>
                    </div>
                    <div class="row">
                         <div class="col-md-12">
                              <div class="form-group">
                                   <label for="password_confirmation">Repite la contraseña</label>
                                   <input type="password" name="password_confirmation" class="form-control"  placeholder="Repite la contraseña">
                              </div>
                         </div>
                    </div>
                    <hr>
                    <button type="submit" class="btn btn-info btn-fill pull-right">Actualizar usuario</button>
                    <a href="{{ route('admin.leader.index') }}" class="btn btn-default btn-fill pull-left">Cancelar</a>
                    <div class="clearfix"></div>
               </div>
          </div>
     </form>
</div>
@can('Editar roles')
<div class="col-md-6 col-sm-6">
     <form class="form" method="post" action="{{ route('admin.leader.permissions.update', $capturist) }}">
          <div class="card ">
               <div class="card-header ">
                    <div class="card-header">
                         <h4 class="card-title">Permisos</h4>
                    </div>
               </div>
               <div class="card-body ">
                    {{ csrf_field() }}
                    {{ method_field('PUT') }}

                    @include('admin.permissions-checkboxes')

                    <hr>
                    <button type="submit" class="btn btn-info btn-fill pull-right">Actualizar usuario</button>

               </div>
          </div>
     </form>
</div>
@endcan
@stop

resources/views/admin/capturist/index.blade.php
@extends('admin.layout')

@section('content')
<div class="col-md-12">
     <div class="card strpied-tabled-with-hover">
          <div class="card-header ">
               <h4 class="card-title">Capturistas</h4>
               <p class="card-category">Lista de capturistas</p>
               <a href="{{ route('admin.capturist.create') }}" class="btn btn-success btn-wd" style="float: right; margin-top: -50px;">
                    <i class="fa fa-plus"></i> Nuevo
               </a>
          </div>
          <div class="card-body table-responsive">
               <table class="table table-hover table-striped table_js">
                    <thead>
                         <tr>
                              <th>ID</th>
                              <th>Nombre</th>
                              <th>Correo</th>
                              <th>Estatus</th>
                              <th class="text-center">Activar</th>
                              <th class="text-center"><i class="nc-icon nc-preferences-circle-rotate"></i></th>
                         </tr>
                    </thead>

                    <tbody>
                         @foreach ($users as $capturist)
                         <tr>
                              <td>{{ $capturist->id }}</td>
                              <td>{{ $capturist->name }}</td>
                              <td>{{ $capturist->email }}</td>
                              <td class="text-center">
                                   @if($capturist->status == 1)
                                   <h6><span class="badge badge-success">Activo</span></h6>
                                   @else
                                   <h6><span class="badge badge-danger">Inactivo</span></h6>
                                   @endif
                              </td>
                              <td class="text-center">
                                   <input type="checkbox" class="l_capturista" value="{{ $capturist->id }}">
                              </td>
                              <td class="text-center">
                                   @can('Ver Capturista')
                                   <a href="{{ route('admin.capturist.show', $capturist) }}"
                                   class="btn btn-sm btn-default btn-outline"
                                   > <i class="fa fa-eye"></i> </a>
                                   @endcan
                                   @can('Editar Capturista')
                                   <a href="{{ route('admin.capturist.edit', $capturist) }}"
                                   class="btn btn-sm btn-info btn-outline"
                                   > <i class="fa fa-pencil"></i> </a>
                                   @endcan
                                   @can('Eliminar Capturista')
                                   <form method="POST"
                                   action="{{ route('admin.capturist.destroy', $capturist) }}"
                                   style="display:inline">
                                   {{ csrf_field() }} {{ method_field('DELETE') }}
                                   <button class="btn btn-sm btn-danger btn-outline"
                                   onclick="return confirm('¿ Estás seguro de querer eliminar este capturista ?')"
                                   >
                                   <i class="fa fa-trash"></i>
                              </button>
                         </form>
                         @endcan

                    </td>
               </tr>
               @endforeach
          </tbody>
          <tfoot>
               <tr>
                    <td colspan="6">
                         <button style="display:none; float:right;" id="btn_activar"  type="button" data-toggle="modal" data-target="#activar_capturistas" class="btn btn-success pull-left">Activar usuarios</button>
                    </td>
               </tr>
          </tfoot>
     </table>
</div>
</div>
</div>



<div class="modal fade modal-mini modal-primary " id="activar_capturistas" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
     <form method="POST" action="{{ route('admin.capturista.activar_capturistas') }}">
          {{ csrf_field() }}
          <div class="modal-dialog">
               <div class="modal-content">
                    <div class="modal-header justify-content-center">
                         <div class="modal-profile">
                              <i class="nc-icon nc-time-alarm"></i>
                         </div>
                    </div>
                    <div class="modal-body text-center">
                         <p> Tiempo actividad : </p>
                         <input type="text" style="text-align:center;" name="tiempo" required class="form-contorl clockpicker" value="">
                         <input type="hidden" name="ip" id="ip" value="">
                         <div id="list_user_active">
                         </div>
                    </div>
                    <div class="modal-footer">
                         <div class="col-md-12">
                              <button type="button" class="btn btn-default btn-simple" data-dismiss="modal">Cancelar</button>
                              <button type="submit" class="btn btn-primary">Activar</button>
                         </div>
                    </div>
               </div>
          </div>
     </form>
</div>

@stop
<!-- Estilos pasarlos al layout -->
@push('style')
<style media="screen">
.popover.clockpicker-popover.bottom.clockpicker-align-left{
    z-index: 9999;
}
</style>

@endpush
<!-- Escripts pasarlos al layout -->
@push('scripts')
<script>
$( document ).ready(function() {

     $.getJSON('https://api.ipify.org?format=json', function(data){
          $('#ip').val(data.ip);
     });

     $('.l_capturista').change(function() {
          var ver_boton = false;
          $('#btn_activar').hide();
          $('#list_user_active').html('');
          $('.l_capturista').each(function () {
               if (this.checked) {
                    $('#btn_activar').show();
                    $('#list_user_active').append('<input type="hidden" name="user[]" value="'+this.value+'" />');
               }
          });

     });

});
</script>
@endpush

resources/views/admin/capturist/show.blade.php
@extends('admin.layout')

@section('content')
<div class="col-md-6">
     <div class="card card-user">
          <div class="card-header no-padding">
               <div class="card-image" style="background-color: #004b8d;">
                    <!-- <img src="/img/background-perfil.jpg" alt="..."> -->
               </div>
          </div>
          <div class="card-body ">
               <div class="author">
                    <a href="#">
                         <img class="avatar border-gray" src="https://us.123rf.com/450wm/tuktukdesign/tuktukdesign1608/tuktukdesign160800042/61010829-icono-de-usuario-hombre-perfil-hombre-de-negocios-avatar-ilustraci%C3%B3n-vectorial-persona-glifo.jpg?ver=6" alt="...">
                    </a>
                    <p class="card-description">
                         <h6 class="card-title">Número identificador</h6>
                         {{ $capturist->id }}
                         <hr>
                         <h6 class="card-title">Nombre completo</h6>
                         {{ $capturist->name }}
                         <hr>
                         <h6 class="card-title">Correo</h6>
                         {{ $capturist->email }}
                         <hr>

                         <h6 class="card-title">Estatus</h6>
                         @if($capturist->status == 1)
                              <h6><span class="badge badge-success">Activo</span></h6>
                         @else
                              <h6><span class="badge badge-danger">Inactivo</span></h6>
                         @endif

                         <hr>

                         <h6 class="card-title">Fecha registro</h6>
                         {{ $capturist->created_at }}
                    </p>
               </div>
          </div>

     </div>
</div>
<div class="col-md-6">
     <div class="card card-user">
          <div class="card-header">
               <h4 class="card-title">Permiso adicionales</h4>
               <p class="card-category">permisos extras asignados </p>
          </div>
          <div class="card-body ">
                    <p class="card-description">
                         @forelse ($capturist->permissions as $permission)
                              <h6 class="card-title">{{ $permission->name }}</h6>
                              @unless($loop>last)
                                   <hr>
                              @endunless
                         @empty
                              <h6 class="card-title">No tiene permisos adicionales</h6>
                         @endforelse
                    </p>
          </div>

     </div>
</div>
@stop