routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Route::get('/', 'PagesController@home');

Route::get('email', function(){
     return new App\Mail\LoginCredencials( App\User::first(), '123434');
});

Route::get('email2', function(){
     return new App\Mail\ActivationCapturist( App\User::first(), date('Y-m-d H:i:s'));
});

Route::group([
     'prefix' => 'admin',
     'namespace' => 'Admin',
     'middleware' => 'auth'],
function(){
     Route::get('/', 'AdminController@index')->name('dashboard');
     Route::resource('user', 'UserController', ['as' => 'admin']);
     Route::resource('leader', 'LeaderController', ['as' => 'admin']);
     Route::resource('capturist', 'CapturistController', ['as' => 'admin']);
     Route::resource('candidate', 'CandidateController', ['as' => 'admin']);
     Route::resource('search', 'SearchController', ['as' => 'admin']);
     Route::resource('company', 'CompanyController', ['as' => 'admin']);
     Route::resource('study', 'StudyController', ['as' => 'admin']);
     Route::resource('category', 'CategoryController', ['as' => 'admin']);
     Route::resource('survey', 'SurveyController', ['as' => 'admin']);

     Route::group(['prefix' => '{category_id}'], function($category_id){
           Route::resource('category', 'CategoryController');
      });

      Route::group(['prefix' => '{user_id}'], function($user_id){
           Route::resource('answer', 'AnswerController');
      });

      Route::get('answer/create/{user_id}/{survey_id}', 'AnswerController@create')->name('answer.create');
      Route::get('answer/edit/{user_id}/{survey_id}', 'AnswerController@edit')->name('answer.edit');

      Route::group(['prefix' => '{category_id}'], function($category_id){
           Route::resource('brand', 'BrandController');
      });

      // Pagina de expotar survey
     Route::get('export_survey/{survey}', 'SurveyController@export_survey')->name('admin.export_survey');

     // Actualizar permisos de usuarios
     Route::put('leader/{user}/permissions', 'UserPermissionsController@update')->name('admin.leader.permissions.update');

     // Activar capturistas
     Route::post('capturista/activar_capturistas', 'CapturistController@activar_capturistas')->name('admin.capturista.activar_capturistas');

     // Pagina de buscador
     Route::get('buscador', 'CandidateController@buscador')->name('admin.buscador');

     // Pagina de buscador
     Route::get('export_search/{search_id}', 'CandidateController@export_search')->name('admin.export_search');

     // Obtener municipios
     Route::get('municipios', 'DireccionesController@municipios')->name('admin.municipios');

     // Obtener localidades
     Route::get('localidades', 'DireccionesController@localidades')->name('admin.localidades');

     // Obtener nuevos candidatos
     Route::get('new_candidate', 'CandidateController@new_candidate')->name('admin.new_candidate');

     // Obtener informar a capturistas
     Route::post('send_comment', 'CandidateController@send_comment')->name('admin.send_comment');

     // Obtener participantes buscador
     Route::get('filter_participants', 'CandidateController@filter_participants')->name('admin.filter_participants');

     // Perfil
     Route::get('perfil', 'CandidateController@perfil')->name('admin.perfil');
     Route::put('edit_perfil', 'CandidateController@edit_perfil')->name('admin.edit_perfil');


     Route::post('assigned_study', 'CandidateController@assigned_study')->name('admin.assigned_study');
     Route::get('assigned_study_id/{id}', 'CandidateController@assigned_study_id')->name('admin.assigned_study_id');
     Route::delete('destroy_assigned_study/{id}', 'CandidateController@destroy_assigned_study')->name('admin.destroy_assigned_study');
});

// Obtener municipios
Route::get('municipios', 'Admin\DireccionesController@municipios')->name('municipios');

// Obtener localidades
Route::get('localidades', 'Admin\DireccionesController@localidades')->name('localidades');

// Desactivar capturistas con cron
Route::get('capturista/desactivar_capturistas', 'PagesController@deactivate_user')->name('capturista.desactivar_capturistas');

// Authentication Routes...
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::get('logout', 'Auth\LoginController@logout')->name('logout');

// Registration Routes...
Route::get('register', 'Admin\CandidateController@showRegistrationForm')->name('register');
Route::put('registro', 'Admin\CandidateController@registro')->name('registro');

// Password Reset Routes...
Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('password/reset', 'Auth\ResetPasswordController@reset');

app/User.php
<?php

namespace App;
use Spatie\Permission\Traits\HasRoles;
use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;
    use HasRoles;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'status', 'last_name_paternal', 'last_name_maternal',
        'date_of_birth', 'phone', 'cell_phone', 'ine_number', 'housewife', 'out_of_home',
        'facebook', 'address', 'commentary', 'photo', 'frecuencia_participacion', 'photo_personal',
        'photo_limpieza','photo_lavado' ,'estado_id','municipio_id','localidad_id','calle',
        'codigo_postal', 'complete_information', 'seen_by_boss', 'user_id', 'boss_message'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];


    public function setPasswordAttribute($password)
    {
         $this->attributes['password'] = bcrypt($password);
    }

    public function brands()
    {
         return $this->belongsToMany(Brand::class)->orderBy('brand_id')->withTimestamps();
    }

    public function brands_old()
    {
         return $this->hasMany(Brand_user_old::class)->orderBy('brand_id');
    }


    public function studys()
    {
         return $this->belongsToMany(Study::class)->withPivot('id');;
    }

     public function get_estado()
     {
          return $this->hasOne(Estado::class, 'id', 'estado_id');
     }

     public function get_municipio()
     {
          return $this->hasOne(Municipio::class, 'id', 'municipio_id');
     }

     public function get_localidad()
     {
          return $this->hasOne(Localidad::class, 'id', 'localidad_id');
     }

     public function surveys()
     {
          return $this->belongsToMany(Survey::class, 'survey_users');
     }

     public function answer()
     {
          return $this->belongsToMany(Answer::class, 'answer_users');
     }
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\User;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Http\Requests\UpdateUserRequest;
use Spatie\Permission\Models\Permission;
use Spatie\Permission\Models\Roles;
use App\Events\UserWasCreated;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
     {
          $users = User::role('Administrador')->get();
          return view('admin.users.index', compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
         $user = new User;
         return view('admin.users.create', compact('user'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
         $data = $request->validate([
             'name' => 'required|string|max:255',
             'email' => 'required|string|email|max:255|unique:users'
        ]);

        $data['status'] = request('status') == 1 ? 1 : 0 ;
        $data['last_name_paternal'] = request('last_name_paternal');
        $data['last_name_maternal'] = request('last_name_maternal');
        $data['password'] = str_random(8);

        $user = User::create($data);

        $user->assignRole('Administrador');

        if ($request->filled('permissions')) {
             $user->givePermissionTo($request->permissions);
        }

        UserWasCreated::dispatch($user, $data['password']);

        return redirect()->route('admin.user.index')->with('success', 'Administrador registrado');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(User $user)
    {
        return view('admin.users.show', compact('user'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
         return view('admin.users.edit', compact('user'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, User $user)
    {
         $data = $request->validate([
             'name' => 'required|string|max:255',
             'email' => 'required|string|email|max:255|unique:users,email,'.$user->id,
        ]);

        if($request->filled('password')) {
           $data =  $request->validate([
                  'password' => 'confirmed', 'min:7',
             ]);
        }

        $data['last_name_paternal'] = request('last_name_paternal');
        $data['last_name_maternal'] = request('last_name_maternal');
        $data['status'] = request('status') == 1 ? 1 : 0 ;

        $user->update( $data );

        return redirect()->route('admin.user.index')->with('success', 'Administrador actualizado');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
          $user->delete();
          return back()->with('success', 'Administrador eliminado');

    }
}

resources/views/admin/users/create.blade.php
@extends('admin.layout')

@section('content')
<div class="col-md-6 ml-auto mr-auto">
     <form class="form" method="post" action="{{ route('admin.user.store') }}">
          {{ csrf_field() }}

          <div class="card">
               <div class="card-header ">
                    <div class="card-header">
                         <h4 class="card-title">Datos personales</h4>
                    </div>
               </div>
               <div class="card-body ">
                    <div class="row">
                         <div class="col-md-12">
                              @if($errors->any())
                                   <ul class="list-group">
                                        @foreach($errors->all() as $key => $error)
                                             <li class="list-group-item list-group-item-danger"> {{ $error }}</li>
                                        @endforeach
                                   </ul>
                              @endif
                         </div>
                         <div class="col-md-12">
                              <div class="row">
                                   <div class="col-md-12">
                                        <div class="form-group">
                                             <label for="name">Nombre(s)</label>
                                             <input type="text" name="name" class="form-control" value="{{ old('name') }}" placeholder="Nombre">
                                        </div>
                                   </div>
                              </div>
                              <div class="row">
                                   <div class="col-md-12">
                                        <div class="form-group">
                                             <label for="name">Apellido Paterno</label>
                                             <input type="text" name="last_name_paternal" class="form-control" value="{{ old('last_name_paternal') }}" placeholder="Apellido Paterno">
                                        </div>
                                   </div>
                              </div>
                              <div class="row">
                                   <div class="col-md-12">
                                        <div class="form-group">
                                             <label for="last_name_maternal">Apellido Materno</label>
                                             <input type="text" name="last_name_maternal" class="form-control" value="{{ old('last_name_maternal') }}" placeholder="Apellido Materno">
                                        </div>
                                   </div>
                              </div>
                              <div class="row">
                                   <div class="col-md-12">
                                        <div class="form-group">
                                             <label for="email">Correo</label>
                                             <input type="email" name="email" class="form-control" value="{{ old('email') }}" placeholder="Correo">
                                        </div>
                                   </div>
                              </div>

                              <div class="row">
                                   <div class="col-md-12">
                                        <div class="form-group">
                                             <label for="status">Estatus</label><br>
                                             <div class="onoffswitch">
                                                 <input type="checkbox" name="status" value="1"  @if( old('status') == 1 ) checked @endif class="onoffswitch-checkbox" id="myonoffswitch">
                                                 <label class="onoffswitch-label" for="myonoffswitch">
                                                     <span class="onoffswitch-inner"></span>
                                                     <span class="onoffswitch-switch"></span>
                                                 </label>
                                             </div>
                                        </div>
                                   </div>
                              </div>
                         </div>

                         <div class="col-md-12">
                              <hr>
                         </div>
                         <div class="col-md-12">
                              <span class="help-block"> La contraseña será generada y enviada al nuevo usuario vía correo.</span>
                         </div>
                         <div class="col-md-12">
                              <hr>
                         </div>
                    </div>

                    <button type="submit" class="btn btn-info btn-fill pull-right">Crear usuario</button>
                    <a href="{{ route('admin.leader.index') }}" class="btn btn-default btn-fill pull-left">Cancelar</a>
                    <div class="clearfix"></div>
               </div>
          </div>

     </form>
</div>
@stop

resources/views/admin/users/edit.blade.php
@extends('admin.layout')

@section('content')
<div class="col-md-6 ml-auto mr-auto">
     <form class="form" method="post" action="{{ route('admin.user.update', $user) }}">
          <div class="card ">
               <div class="card-header ">
                    <div class="card-header">
                         <h4 class="card-title">Datos personales</h4>
                    </div>
               </div>
               <div class="card-body ">
                    <div class="row">
                         <div class="col-md-12">
                              @if($errors->any())
                                   <ul class="list-group">
                                        @foreach($errors->all() as $key => $error)
                                             <li class="list-group-item list-group-item-danger"> {{ $error }}</li>
                                        @endforeach
                                   </ul>
                              @endif
                         </div>
                    </div>
                    <div class="row">
                         {{ csrf_field() }} {{ method_field('PUT') }}
                         <div class="col-md-12">
                              <div class="form-group">
                                   <label for="name">Nombre</label>
                                   <input type="text" name="name" class="form-control" value="{{ old('name', $user->name) }}" placeholder="Nombre">
                              </div>
                         </div>

                    </div>
                    <div class="row">
                         <div class="col-md-12">
                              <div class="form-group">
                                   <label for="email">Correo</label>
                                   <input type="email" name="email" class="form-control" value="{{ old('email', $user->email) }}" placeholder="Correo">
                              </div>
                         </div>
                    </div>
                    <div class="row">
                         <div class="col-md-12">
                              <div class="form-group">
                                   <label for="status">Estatus</label><br>
                                   <div class="onoffswitch">
                                       <input type="checkbox"
                                        name="status"
                                        value="1"
                                        @if( old('status', $user->status) == 1 ) checked @endif
                                        class="onoffswitch-checkbox"
                                        id="myonoffswitch" >
                                       <label class="onoffswitch-label" for="myonoffswitch">
                                           <span class="onoffswitch-inner"></span>
                                           <span class="onoffswitch-switch"></span>
                                       </label>
                                   </div>
                              </div>
                         </div>
                    </div>

                    <div class="row">
                         <div class="col-md-12">
                              <div class="form-group">
                                   <label for="password">Contraseña</label>
                                   <input type="password" name="password" class="form-control"  placeholder="Contraseña">
                                   <span class="help-block">Dejar en blanco para no cambiar la contraseña</span>
                              </div>
                         </div>
                    </div>
                    <div class="row">
                         <div class="col-md-12">
                              <div class="form-group">
                                   <label for="password_confirmation">Repite la contraseña</label>
                                   <input type="password" name="password_confirmation" class="form-control"  placeholder="Repite la contraseña">
                              </div>
                         </div>
                    </div>

                    <hr>
                    <button type="submit" class="btn btn-info btn-fill pull-right">Actualizar usuario</button>
                    <a href="{{ route('admin.user.index') }}" class="btn btn-default btn-fill pull-left">Cancelar</a>
                    <div class="clearfix"></div>
               </div>
          </div>
     </form>
</div>

@stop

resources/views/admin/users/index.blade.php
@extends('admin.layout')

@section('content')
<div class="col-md-12">
     <div class="card strpied-tabled-with-hover">
          <div class="card-header ">
               <h4 class="card-title">Administradores</h4>
               <p class="card-category">Lista de administradores</p>
               <a href="{{ route('admin.user.create') }}" class="btn btn-success btn-wd" style="float: right; margin-top: -50px;">
                    <i class="fa fa-plus"></i> Nuevo
               </a>
          </div>
          <div class="card-body table-responsive">
               <table class="table table-hover table-striped table_js">
                    <thead>
                         <tr>
                              <th>ID</th>
                              <th>Nombre</th>
                              <th>Correo</th>
                              <th class="text-center">Estatus</th>
                              <th class="text-center"><i class="nc-icon nc-preferences-circle-rotate"></i></th>
                         </tr>
                    </thead>
                    <tbody>
                         @foreach ($users as $user)
                         <tr>
                              <td>{{ $user->id }}</td>
                              <td>{{ $user->name }}</td>
                              <td>{{ $user->email }}</td>
                              <td class="text-center">
                                   @if($user->status == 1)
                                        <h6><span class="badge badge-success">Activo</span></h6>
                                   @else
                                        <h6><span class="badge badge-danger">Inactivo</span></h6>
                                   @endif
                              </td>
                              <td class="text-center">
                                   @can('Ver Administradores')
                                   <a href="{{ route('admin.user.show', $user) }}"
                                        class="btn btn-sm btn-default btn-outline"
                                   > <i class="fa fa-eye"></i> </a>
                                   @endcan
                                   @can('Editar Administradores')
                                   <a href="{{ route('admin.user.edit', $user) }}"
                                        class="btn btn-sm btn-info btn-outline"
                                   > <i class="fa fa-pencil"></i> </a>
                                   @endcan
                                   @can('Eliminar Administradores')
                                   <form method="POST"
                                        action="{{ route('admin.user.destroy', $user) }}"
                                        style="display:inline">
                                        {{ csrf_field() }} {{ method_field('DELETE') }}
                                        <button class="btn btn-sm btn-danger btn-outline"
                                             onclick="return confirm('¿ Estás seguro de querer eliminar este administrador ?')"
                                         >
                                         <i class="fa fa-trash"></i>
                                        </button>
                                   </form>
                                   @endcan
                              </td>
                         </tr>
                         @endforeach
                    </tbody>
               </table>
          </div>
     </div>
</div>
@stop

resources/views/admin/users/show.blade.php
@extends('admin.layout')

@section('content')
<div class="col-md-6 ml-auto mr-auto">
     <div class="card card-user">
          <div class="card-header no-padding">
               <div class="card-image" style="background-color: #004b8d;">
                    <!-- <img src="/img/background-perfil.jpg" alt="..."> -->
               </div>
          </div>
          <div class="card-body ">
               <div class="author">
                    <a href="#">
                         <img class="avatar border-gray" src="https://us.123rf.com/450wm/tuktukdesign/tuktukdesign1608/tuktukdesign160800042/61010829-icono-de-usuario-hombre-perfil-hombre-de-negocios-avatar-ilustraci%C3%B3n-vectorial-persona-glifo.jpg?ver=6" alt="...">
                    </a>
                    <p class="card-description">
                         <h6 class="card-title">Número identificador</h6>
                         {{ $user->id }}
                         <hr>
                         <h6 class="card-title">Nombre completo</h6>
                         {{ $user->name }}
                         <hr>
                         <h6 class="card-title">Correo</h6>
                         {{ $user->email }}
                         <hr>

                         <h6 class="card-title">Estatus</h6>
                         @if($user->status == 1)
                              <h6><span class="badge badge-success">Activo</span></h6>
                         @else
                              <h6><span class="badge badge-danger">Inactivo</span></h6>
                         @endif

                         <hr>

                         <h6 class="card-title">Fecha registro</h6>
                         {{ $user->created_at }}
                    </p>
               </div>
          </div>

     </div>
</div>
@stop