routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Route::get('/', 'PagesController@home');

Route::get('email', function(){
     return new App\Mail\LoginCredencials( App\User::first(), '123434');
});

Route::get('email2', function(){
     return new App\Mail\ActivationCapturist( App\User::first(), date('Y-m-d H:i:s'));
});

Route::group([
     'prefix' => 'admin',
     'namespace' => 'Admin',
     'middleware' => 'auth'],
function(){
     Route::get('/', 'AdminController@index')->name('dashboard');
     Route::resource('user', 'UserController', ['as' => 'admin']);
     Route::resource('leader', 'LeaderController', ['as' => 'admin']);
     Route::resource('capturist', 'CapturistController', ['as' => 'admin']);
     Route::resource('candidate', 'CandidateController', ['as' => 'admin']);
     Route::resource('search', 'SearchController', ['as' => 'admin']);
     Route::resource('company', 'CompanyController', ['as' => 'admin']);
     Route::resource('study', 'StudyController', ['as' => 'admin']);
     Route::resource('category', 'CategoryController', ['as' => 'admin']);
     Route::resource('survey', 'SurveyController', ['as' => 'admin']);

     Route::group(['prefix' => '{category_id}'], function($category_id){
           Route::resource('category', 'CategoryController');
      });

      Route::group(['prefix' => '{user_id}'], function($user_id){
           Route::resource('answer', 'AnswerController');
      });

      Route::get('answer/create/{user_id}/{survey_id}', 'AnswerController@create')->name('answer.create');
      Route::get('answer/edit/{user_id}/{survey_id}', 'AnswerController@edit')->name('answer.edit');

      Route::group(['prefix' => '{category_id}'], function($category_id){
           Route::resource('brand', 'BrandController');
      });

      // Pagina de expotar survey
     Route::get('export_survey/{survey}', 'SurveyController@export_survey')->name('admin.export_survey');

     // Actualizar permisos de usuarios
     Route::put('leader/{user}/permissions', 'UserPermissionsController@update')->name('admin.leader.permissions.update');

     // Activar capturistas
     Route::post('capturista/activar_capturistas', 'CapturistController@activar_capturistas')->name('admin.capturista.activar_capturistas');

     // Pagina de buscador
     Route::get('buscador', 'CandidateController@buscador')->name('admin.buscador');

     // Pagina de buscador
     Route::get('export_search/{search_id}', 'CandidateController@export_search')->name('admin.export_search');

     // Obtener municipios
     Route::get('municipios', 'DireccionesController@municipios')->name('admin.municipios');

     // Obtener localidades
     Route::get('localidades', 'DireccionesController@localidades')->name('admin.localidades');

     // Obtener nuevos candidatos
     Route::get('new_candidate', 'CandidateController@new_candidate')->name('admin.new_candidate');

     // Obtener informar a capturistas
     Route::post('send_comment', 'CandidateController@send_comment')->name('admin.send_comment');

     // Obtener participantes buscador
     Route::get('filter_participants', 'CandidateController@filter_participants')->name('admin.filter_participants');

     // Perfil
     Route::get('perfil', 'CandidateController@perfil')->name('admin.perfil');
     Route::put('edit_perfil', 'CandidateController@edit_perfil')->name('admin.edit_perfil');


     Route::post('assigned_study', 'CandidateController@assigned_study')->name('admin.assigned_study');
     Route::get('assigned_study_id/{id}', 'CandidateController@assigned_study_id')->name('admin.assigned_study_id');
     Route::delete('destroy_assigned_study/{id}', 'CandidateController@destroy_assigned_study')->name('admin.destroy_assigned_study');
});

// Obtener municipios
Route::get('municipios', 'Admin\DireccionesController@municipios')->name('municipios');

// Obtener localidades
Route::get('localidades', 'Admin\DireccionesController@localidades')->name('localidades');

// Desactivar capturistas con cron
Route::get('capturista/desactivar_capturistas', 'PagesController@deactivate_user')->name('capturista.desactivar_capturistas');

// Authentication Routes...
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::get('logout', 'Auth\LoginController@logout')->name('logout');

// Registration Routes...
Route::get('register', 'Admin\CandidateController@showRegistrationForm')->name('register');
Route::put('registro', 'Admin\CandidateController@registro')->name('registro');

// Password Reset Routes...
Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('password/reset', 'Auth\ResetPasswordController@reset');

resources/views/admin/partials/flash-message.blade.php
@if ($message = Session::get('success'))
<div class="alert alert-success alert-block">
	<button type="button" class="close" data-dismiss="alert">×</button>
        <strong>{{ $message }}</strong>
</div>
@endif


@if ($message = Session::get('error'))
<div class="alert alert-danger alert-block">
	<button type="button" class="close" data-dismiss="alert">×</button>
        <strong>{{ $message }}</strong>
</div>
@endif


@if ($message = Session::get('warning'))
<div class="alert alert-warning alert-block">
	<button type="button" class="close" data-dismiss="alert">×</button>
	<strong>{{ $message }}</strong>
</div>
@endif


@if ($message = Session::get('info'))
<div class="alert alert-info alert-block">
	<button type="button" class="close" data-dismiss="alert">×</button>
	<strong>{{ $message }}</strong>
</div>
@endif


@if ($errors->any())
<div class="alert alert-danger">
	<button type="button" class="close" data-dismiss="alert">×</button>
     Por favor, consulte el siguiente formulario para ver si hay errores
</div>
@endif
<style media="screen">
     .alert button.close{
          right: 25px;
          top: 40%;
     }
</style>

resources/views/admin/partials/nav.blade.php
<ul class="nav">
     <li class="nav-item ">
          <a class="nav-link" href="{{ route('dashboard') }}">
               <i class="nc-icon nc-chart-pie-35"></i>
               <p>Panel principal</p>
          </a>
     </li>
     @can('Ver Administradores')
     <li class="nav-item ">
          <a class="nav-link" href="{{ route('admin.user.index') }}">
               <i class="nc-icon nc-badge"></i>
               <p>Administradores</p>
          </a>
     </li>
     @endcan
     @can('Ver Jefe Capturista')
     <li class="nav-item ">
          <a class="nav-link" href="{{ route('admin.leader.index') }}">
               <i class="nc-icon nc-bag"></i>
               <p>Jefe Capturistas</p>
          </a>
     </li>
     @endcan
     @can('Ver Capturista')
     <li class="nav-item ">
          <a class="nav-link" href="{{ route('admin.capturist.index') }}">
               <i class="nc-icon nc-single-copy-04"></i>
               <p>Capturistas</p>
          </a>
     </li>
     @endcan
     @can('Ver Cantidato')
     <li class="nav-item ">
          <a class="nav-link" href="{{ route('admin.candidate.index') }}">
               <i class="nc-icon nc-satisfied"></i>
               <p>Participantes</p>
          </a>
     </li>

     <li class="nav-item ">
          <a class="nav-link" href="{{ route('admin.search.index') }}">
               <i class="nc-icon nc-zoom-split"></i>
               <p>Buscar participantes</p>
          </a>
     </li>

     <li class="nav-item ">
          <a class="nav-link" href="{{ route('admin.company.index') }}">
               <i class="fa fa-building-o" aria-hidden="true"></i>
               <p>Cliente / Empresa</p>
          </a>
     </li>

     <li class="nav-item ">
          <a class="nav-link" href="{{ route('admin.study.index') }}">
               <i class="fa fa-briefcase" aria-hidden="true"></i>
               <p>Estudio</p>
          </a>
     </li>

     <li class="nav-item ">
          <a class="nav-link" href="{{ route('admin.category.index') }}">
               <i class="fa fa-sitemap" aria-hidden="true"></i>
               <p>Categorías / Productos</p>
          </a>
     </li>

     <li class="nav-item ">
          <a class="nav-link" href="{{ route('admin.survey.index') }}">
               <i class="fa fa-check-square-o" aria-hidden="true"></i>
               <p>Encuestas</p>
          </a>
     </li>
     @endcan
     <?php $user = App\User::where('id', auth()->user()->id)->first(); ?>
     <?php if($user->hasRole('Candidato')): ?>
          <li class="nav-item ">
               <a class="nav-link" href="{{ route('admin.perfil') }}">
                    <i class="nc-icon nc-badge"></i>
                    <p>Perfil</p>
               </a>
          </li>
          <li class="nav-item ">
               <a class="nav-link" href="{{ route('answer.index', ['user_id' => auth()->user()->id]) }}">
                    <i class="fa fa-check-square-o" aria-hidden="true"></i>
                    <p>Encuestas</p>
               </a>
          </li>
     <?php endif; ?>
</ul>

resources/views/admin/partials/notification_candidate.blade.php
<a href="#" class="dropdown-toggle nav-link" data-toggle="dropdown">
     <i class="nc-icon nc-email-83"></i>
     <span class="notification" id="count_noti">0</span>
     <span class="d-lg-none">Notification</span>
</a>
<ul class="dropdown-menu  dropdown-menu-right" id="link_new">

</ul>
@push('scripts')
<script>
$( document ).ready(function() {
     existen_nuevos()
});


setInterval('existen_nuevos()', 8000);

var pr = 0;
function existen_nuevos() {
     $.ajax({
          url: "{{ route('admin.new_candidate') }}",
          type:'get',
          success:  function (response) {
               $('#link_new').html('');
               $('span#count_noti').html(response.length);
               $.each(response, function( index, value ) {
                    $( "#link_new" ).append( '<a class="dropdown-item" href="{{ url("admin/candidate/") }}/'+value.id+'">Candidato '+value.name+'</a>' );
               });
          },
          error:function(x,xs,xt){
               window.open(JSON.stringify(x));
               //alert('error: ' + JSON.stringify(x) +"\n error string: "+ xs + "\n error throwed: " + xt);
          }
     });
     pr++;
     console.log(pr);
}


</script>
@endpush